export const STUDY_INIT_QUEUE = 'STUDY_INIT_QUEUE';

export const STUDY_GET_QUEUE = 'STUDY_GET_QUEUE';



export const STUDY_ADVANCE = 'STUDY_ADVANCE';
export const STUDY_ADVANCE_RED = 'STUDY_ADVANCE_RED';
export const STUDY_ADVANCE_ORANGE = 'STUDY_ADVANCE_ORANGE';
export const STUDY_ADVANCE_GREEN = 'STUDY_ADVANCE_GREEN';


export const STUDY_FINISH_SESSION = 'STUDY_FINISH_SESSION'; // displays a finished screen




export const BROWSE_LOAD = 'BROWSE_LOAD';
